declare module "react-native-sms-listener" {
  export interface Receipt {
    /** Unique ID generated by native module */
    id: string;

    /** Phone number or contact name of the sender */
    sender: string;

    /** The SMS body text */
    body: string;

    /** Message timestamp in ms since epoch */
    timestamp: number;

    /** Timestamp when the library captured the SMS */
    capturedAt: number;

    /** Matched target name (if any) */
    matchedTarget: string;
  }

  /** Starts listening for SMS messages from a specific contact name */
  export function startCapture(contactName: string): Promise<void>;

  /** Stops background SMS listening */
  export function stopCapture(): Promise<void>;

  /** Returns whether SMS capture is currently active */
  export function isCaptureActive(): Promise<boolean>;

  /** Fetch receipts stored by the native module while app was inactive */
  export function getStoredReceipts(): Promise<Receipt[]>;

  /** Clears the stored receipts cache */
  export function clearStoredReceipts(): Promise<boolean>;

  const SmsReceiptListener: {
    startCapture: typeof startCapture;
    stopCapture: typeof stopCapture;
    isCaptureActive: typeof isCaptureActive;
    getStoredReceipts: typeof getStoredReceipts;
    clearStoredReceipts: typeof clearStoredReceipts;
  };

  export default SmsReceiptListener;
}
